import { errors } from './errors.js';

export default {
  languages: { sr: 'SR', en: 'EN' },
  meta: { title: 'RADE KOMŠA — GOD OF MID | Temple of the Eternal Midlaner', description: '5,000 years of dominance. Not one worthy opponent. Enter the temple of RADE KOMŠA, Pharaoh of the Midlane and grandmaster of Life Chess.' },
  a11y: { skip: 'Skip to main content', nav: 'Main navigation', language: 'Choose language', sr: 'Srpski', en: 'English', home: 'RADE KOMŠA — home', quoteClose: 'Dismiss prophecy', pause: 'Pause motion', resume: 'Resume motion', emblem: 'Request a prophecy from the pharaoh', stats: 'Statistics of pharaonic dominance', chess: 'Request a Life Chess move', judgment: 'Divine judgment: worthy of an attempt' },
  nav: { brand: 'RADE', sub: 'MIDLANE DYNASTY', mythology: 'Sacred records', chess: 'Life Chess', why: 'Why challenge', faq: 'Mortal questions', challenge: 'CHALLENGE' },
  hero: {
    era: 'SINCE 3000 BC / STILL UNNERFED', status: 'DIVINE SYSTEM ONLINE', pretitle: 'PHARAOH OF THE MIDLANE', name: 'RADE KOMŠA', title: 'GOD OF MID', subtitle: '5,000 YEARS OF DOMINANCE.\nNOT ONE WORTHY OPPONENT.', description: 'Records of his first match were lost in the fall of the Library of Alexandria. Archaeologists have yet to uncover evidence of Rade losing mid.', valve: 'Valve declined to comment.', cta: 'CHALLENGE THE PHARAOH AND WIN 50E', support: 'One button. One application. One pharaoh awaiting proof.', warning: 'RADE KOMŠA does not guarantee the preservation of MMR, confidence, or dignity.', visualTop: 'DIVINE ENTITY IDENTIFIED', visualId: 'DYNASTY / 001', visualLabel: 'THE ETERNAL MIDLANER', visualNote: 'ANUBIS OF THE RIVER · KEEPER OF THE ANCIENT', coord: 'GIZA / MID CORRIDOR', power: 'POWER: UNMEASURABLE', node: 'PYRAMID GPU CLUSTER', uptime: 'UPTIME: 5,000 YEARS',
    rotations: ['HE DOES NOT PLAY MID. MID PLAYS HIM.', 'HE DOES NOT READ THE MAP. THE MAP READS HIM.', 'THE ANCIENT WAS BUILT IN HIS HONOR.', 'BEFORE DOTA, THERE WAS CHESS. BEFORE CHESS, THERE WAS RADE.', 'EGYPT HAD MANY GODS. THE MIDLANE NEEDED ONLY ONE NAME.', 'RADE KOMŠA.'],
    badges: ['ANCIENT AI POWERED', '14.7T DIVINE PARAMETERS', 'DOTA 2 VERIFIED*'],
  },
  ticker: 'RADE KOMŠA // GOD OF MID // LIFE CHESS GRANDMASTER // PHARAOH OF THE MIDLANE // ANUBIS PROTOCOL ACTIVE // RUN, NOOBS // THEOLOGICAL MID DIFF // DIVINE QUEUE OPEN //',
  stats: [
    { label: 'MIDLANE WIN RATE', note: 'The other 0.03% is a papyrus translation error.' },
    { label: 'CHALLENGERS DEFEATED', note: 'Anubis keeps the records. By hand.' },
    { label: 'ENEMY MORALE AT 10 MIN', note: 'The soul has already left the laning phase.' },
    { label: 'TOWERS DENIED HUMAN RIGHTS', note: 'Geneva Convention module not loaded.' },
  ],
  oracle: {
    eyebrow: '01 / TECHNOLOGY BEFORE TECHNOLOGY', title: 'A GOD COMPLEX.\nNOW WITH AN API.', description: 'The pyramids were never tombs. They were the first matchmaking servers. We just added RGB.', confidence: 'PROPHECY CONFIDENCE', review: 'PEER REVIEWED BY RADE. APPROVED BY RADE.', name: 'RADE ORACLE™', subtitle: 'NEURAL PHARAOH ENGINE', status: 'CONNECTED TO ETERNITY', chart: 'FIG 01 — GPU-OPTIMIZED PROPHECY', gpu: 'GPU: 4,096 × SARCOPHAGUS H100', action: 'CONSULT THE ORACLE',
    telemetry: [
      { label: 'LAST HIT', value: 'PREORDAINED' }, { label: 'DENIES', value: 'CANONICAL' }, { label: 'RUNE CONTROL', value: 'DIVINE' }, { label: 'LIFE CHESS DEPTH', value: '∞' }, { label: 'GANK SURVIVAL', value: 'IRRELEVANT' }, { label: 'ENEMY MORALE', value: 'COLLAPSING' }, { label: 'ANUBIS CONNECTION', value: 'ACTIVE' }, { label: 'PYRAMID NODE', value: 'ONLINE' }, { label: 'ANCIENT STATUS', value: 'DEFENDED' }, { label: 'MID DIFFERENCE', value: 'THEOLOGICAL' },
    ],
  },
  mythology: {
    eyebrow: '02 / THE ARCHIVE OF INDISPUTABLE FACT', title: 'RECORDS FROM THE TEMPLE OF MID', description: 'History is written by the winner. So, Rade.', tablet: 'PAPYRUS', action: 'READ BETWEEN THE HIEROGLYPHS',
    facts: [
      { id: 'first-creep', title: 'THE GENESIS OF CREEPS', text: 'The first creep was spawned so Rade would have something to last hit.' },
      { id: 'roshan', title: 'FORBIDDEN ETYMOLOGY', text: 'Roshan was originally named Radeshan. The interface ran out of room.' },
      { id: 'international', title: 'THE FIRST INTERNATIONAL', text: 'The International was founded after a failed attempt to locate a worthy opponent.' },
      { id: 'runes', title: 'THE COSMIC SCHEDULE', text: 'Runes appear every two minutes because that is how long the universe can survive without paying tribute to Rade.' },
      { id: 'fog', title: 'THE MERCY OF THE FOG', text: 'Fog of War exists because ordinary humans cannot safely witness everything Rade sees.' },
      { id: 'mmr', title: 'THE LIMITS OF MATHEMATICS', text: 'MMR measures your distance from Rade. 10,000 is a limit of the measuring instrument. Not of Rade.' },
    ],
  },
  archaeology: { label: 'ARCHAEOLOGICAL REPORT #322', title: 'THE INSCRIPTION THAT CHANGED SCIENCE.', text: 'On the wall of a tomb in Giza, archaeologists found an inscription roughly translating to:', inscription: 'mid or feed', age: 'Estimated age of the inscription: 4,700 years.', note: 'Peer review pending.', coordinate: 'GIZA PLATEAU / STRATUM 7.39', seal: 'AUTHENTIC\nBY RADE’S DECREE' },
  chess: {
    eyebrow: '03 / STRATEGY BEYOND EXISTENCE', title: 'LIFE CHESS™', subtitle: 'Dota is merely the board.', text: 'While his opponent considers the next move, Rade considers the next seven lifetimes.', detail: 'An ordinary person sees 64 squares. Rade sees an infinite board.', doctrine: 'Every gank is a gambit.\nEvery creep is a piece.\nEvery enemy defeat is theoretically expected.', name: 'LIFE CHESS ENGINE', depth: 'DEPTH', variations: 'CALCULATED VARIATIONS', opponent: 'OPPONENT FUTURE', known: 'KNOWN', rade: 'RADE FUTURE', classified: 'CLASSIFIED', move: 'CHECKMATE IN SEVEN LIFETIMES', grandmaster: 'GRANDMASTER OF THE ETERNAL CHESSBOARD', action: 'REQUEST THE NEXT MOVE',
  },
  why: { eyebrow: '02 / GOLD, HONOR, AND POOR DECISIONS', title: 'WHY CHALLENGE RADE?', note: 'THREE REWARDS. ONE MAY BE FINANCIAL.', cards: [
    { title: 'WIN 50 EUROS', text: 'If the temple accepts the proof and Rade falls, the pharaoh’s gold becomes yours. Anubis has not yet decreed the tax.', label: 'SARCOPHAGUS PRIZE FUND' },
    { title: 'CLAIM ETERNAL HONOR', text: 'A win over Rade is worth more than MMR: you may say you outplayed the man whose ego has its own pyramid.', label: 'KEEPER OF THE MIDLANE' },
    { title: 'ENTER THE PAPYRI', text: 'Even defeat leaves a mark. Your name joins the mortals who approached the pharaoh and still clicked final submit.', label: 'ARCHIVE OF THE BRAVE AND UNWISE' },
  ] },
  science: { label: 'THE SCIENCE IS SETTLED™', text: '“After billions of neural simulations, no reliable evidence of a superior midlaner has been discovered.”', author: '— RADE INSTITUTE OF RADE-RELATED RESEARCH' },
  failures: {
    eyebrow: '03 / ARCHIVE OF REJECTED MORTALS', title: 'FAILED\nCHALLENGES', description: 'Before claiming your 50 euros, observe what happened to those who believed they could dispute the prophecy.', unsupported: 'Your browser cannot display this archival record.',
    entries: [
      { title: 'ARCHIVAL RECORD 0922', verdict: 'JUDGMENT: THE TEMPLE IS UNIMPRESSED', aria: 'Play failed challenge video, archival record 0922' },
      { title: 'ARCHIVAL RECORD 0924', verdict: 'JUDGMENT: THE PHARAOH REMAINS UNCHALLENGED', aria: 'Play failed challenge video, archival record 0924' },
    ],
  },
  bait: {
    challenge: 'CHALLENGE',
    immortal: 'PROVE HE IS NOT IMMORTAL',
    better: 'PROVE YOU ARE BETTER',
    noob: 'PROVE HE IS A NOOB',
  },
  challenge: {
    back: 'Back to the temple',
    eyebrow: 'SOCIAL RACE / DOTA IS ONLY THE TOOL',
    title: 'HOW TO WIN 50 EUROS',
    lead: 'You do not win this by clicking an MMR field. You win with proof, pressure, negotiation, and an aura that can survive Rade looking back.',
    reward: '50 EUROS',
    rewardNote: 'The prize for proof the temple accepts as bold enough.',
    howTitle: 'Prove one of three things',
    rules: [
      'PROVE THE FAIRY TALES ABOUT RADEKOMSA NOT BEING IMMORTAL ARE TRUE',
      'PROVE YOU ARE BETTER THAN RADEKOMSA THE PHARAOH',
      'PROVE YOU HAVE THE AURA',
    ],
    social: 'Each of these is a social race. Dota is only the tool. Everything is accepted: 1v1, 5v5, 3v3 if you agree on it.',
    modes: ['1v1', '3v3', '5v5', 'TEMPLE DEAL'],
    discord: 'Enter Discord, start the adventure, and bring proof.',
  },
  signup: {
    eyebrow: '01 / YOUR NAME. HIS STATISTIC.', title: 'CHALLENGER\nPROTOCOL', subtitle: 'The temple will choose one challenger it believes is worthy. We will contact them and invite them to fight for 50 euros. Until then, the temple remembers every answer, even after a reload.', warning: 'CONFIDENCE IS NOT A QUALIFICATION.', warningText: 'The temple accepts all MMR brackets.\nRade recognizes none of them.', facts: ['FIVE STEPS', 'DRAFT SAVED', 'ONE PHARAOH'], exit: 'You can revisit every answer before the final submission.', panel: 'BOOK OF CHALLENGERS / V.03', status: 'ACCEPTING MORTALS', saved: 'DRAFT SAVED', progressLabel: 'Challenger protocol progress', stepCounter: 'STEP', yes: 'YES', no: 'NO', unanswered: 'UNANSWERED', next: 'CONTINUE', back: 'BACK',
    step1: { kicker: 'I / MORTALITY STATUS', question: 'ARE YOU ALSO IMMORTAL, AND DO YOU BELIEVE YOU ARE A WORTHY OPPONENT?', hint: 'Two claims. One decision. Rade already knows the truth.' },
    step2: { kicker: 'II / HERESY TEST', question: 'DO YOU BELIEVE THE LIE THAT RADE KOMŠA IS NOT IMMORTAL?', hint: 'Choose an answer. Then collect all five seals of pharaonic bureaucracy.' },
    step3: { kicker: 'III / EGO CALIBRATION', question: 'DO YOU THINK YOU ARE BETTER THAN RADE KOMŠA?', hint: 'YES evades you and stays locked for 300 seconds. Only then does the pharaoh permit a click. NO is available immediately.' },
    pursuit: { locked: 'THE PHARAOH DOES NOT YET PERMIT YES', remaining: 'UNLOCKS IN', unlocked: '300 SECONDS HAVE PASSED. YES IS NOW AVAILABLE.', denied: 'Click denied. Anubis does not recognize shortcuts.', note: 'The countdown starts when this question opens. The temple remembers the time even after a page reload.' },
    heresyWarnings: {
      label: 'WARNING / TEMPLE OF MID', counter: 'SEAL', ok: 'OK', escape: 'Esc closes the warnings and returns to the question. Your answer is confirmed only after all five seals.',
      entries: [
        { title: 'ANUBIS ALREADY KNOWS.', message: 'Warning: Pharaoh Anubis will know your answer. He already does, actually. This window is for the paperwork.' },
        { title: 'THEOLOGY ACCEPTS NO APPEALS.', message: 'Pharaoh Anubis is the GOD OF MID. You cannot click NO. If you already did, your mouse will be summoned for questioning.' },
        { title: 'YOUR EGO IS ON THE SCALES.', message: 'Your confidence goes on one side. Rade’s last hit goes on the other. The scales have just submitted their resignation.' },
        { title: 'THE PAPYRUS REMEMBERS.', message: 'Your answer will be carved into a pyramid wall. Clearing browser history does not clear the history of civilization.' },
        { title: 'THE FINAL SEAL. FOR NOW.', message: 'By clicking OK, you acknowledge five separate warnings. The pharaoh reserves the right to classify your opinion as decoration.' },
      ],
    },
    step4: { kicker: 'IV / CHALLENGER IDENTITY', question: 'WHO DARES APPROACH THE MIDLANE?', hint: 'Leave the details that will be entered into the Book of Challengers.' },
    step5: { kicker: 'V / FINAL JUDGMENT', question: 'DO YOU STAND BEHIND THIS CHALLENGE?', hint: 'Review your answers. This is the only step that submits the application.' },
    name: 'NAME OR NICK', mmr: 'DOTA 2 MMR', description: 'WHY ARE YOU WORTHY?', required: 'REQUIRED', honest: 'BE HONEST. HE KNOWS.', descriptionLimit: 'UP TO 500 CHARACTERS', namePlaceholder: 'e.g. xX_MidGod_420_Xx', mmrPlaceholder: '5000', descriptionPlaceholder: 'Briefly explain why you deserve a midlane match against Rade...', honeypot: 'Leave this empty', analysis: 'RADE AI is ready to record your decision.', submit: 'SUBMIT FINAL CHALLENGE', private: 'The application is stored privately in Netlify Forms. Your dignity is not covered.', privacy: 'How your data is stored',
    reviewImmortal: 'IMMORTAL AND WORTHY', reviewLies: 'BELIEVES THE LIE', reviewBetter: 'BETTER THAN RADE', reviewName: 'CHALLENGER', reviewMmr: 'MMR', reviewDescription: 'REASON',
    processingLabel: 'ANCIENT EVALUATION IN PROGRESS', processingNote: 'Do not disconnect your delusions.', awaiting: 'AWAITING CONFIRMATION FROM THE BOOK...',
    stages: ['CONNECTING TO THE ANCIENT SERVER...', 'SCANNING STEAM IDENTITY...', 'CALIBRATING MMR...', 'ANALYZING MIDLANE DELUSION...', 'CONSULTING ANUBIS...', 'SIMULATING 14,882,943 MATCHUPS...', 'RADE NEURAL CORE IS PASSING JUDGMENT...'],
    acceptedLabel: 'JUDGMENT RECORDED', accepted: 'APPLICATION ACCEPTED.', acceptedText: 'Your name is inscribed in the Book of Challengers.', survival: 'Predicted survival probability:', survivalNote: 'An oracle prediction. No scientific value.', luck: 'Good luck.\nYou will require it.', return: 'RETURN TO THE MORTAL REALM', stamp: 'WORTHY OF AN ATTEMPT', stampNote: 'Worthy of an attempt does not mean worthy of Rade.', judgmentLabel: 'ANUBIS HAS WEIGHED YOUR MMR',
  },
  faq: { eyebrow: '04 / ANSWERS CARVED IN STONE', title: 'QUESTIONS FREQUENTLY\nASKED BY MORTALS', description: 'Doubt is human. The answers are final.', entries: [
    { id: 'doctor', question: 'IS RADE KOMŠA A DOCTOR?', answer: 'YES.\nRADE KOMŠA IS A DOCTOR OF EVERY HERO.\nHis diploma has not been recovered because paper was invented after his specialization.' },
    { id: 'heroes', question: 'DOES RADE KOMŠA PLAY EVERY HERO?', answer: 'Wrong question.\nThe heroes play for RADE.' },
    { id: 'main', question: 'WHAT IS RADE’S MAIN HERO?', answer: 'DOTA 2.' },
    { id: 'rating', question: 'HOW MUCH MMR DOES RADE HAVE?', answer: 'The MMR system does not currently support a number of the required width.' },
    { id: 'lost', question: 'HAS RADE EVER LOST MID?', answer: 'No reliable historical sources confirm such an event.\n\nSome opponents claim otherwise.\nTheir Steam profiles are no longer relevant to the investigation.' },
    { id: 'pharaoh', question: 'IS RADE A PHARAOH?', answer: 'Historians use the term “pharaoh” because modern science has yet to develop a more precise designation.' },
    { id: 'god', question: 'IS RADE THE GOD OF MID?', answer: 'This is an FAQ, not a venue for debating established facts.' },
    { id: 'anubis', question: 'WHY IS ANUBIS ON THIS WEBSITE?', answer: 'Anubis handles the opponents after the laning phase.' },
    { id: 'chess', question: 'DOES RADE PLAY CHESS?', answer: 'Rade does not play chess.\nRade plays Life Chess.\nChess is the simplified edition.' },
    { id: 'gank', question: 'CAN RADE BE GANKED?', answer: 'Theoretically, yes.\nExperimental confirmation has not yet been successfully reproduced.' },
    { id: 'challengers', question: 'WHY DO CHALLENGERS SIGN UP?', answer: 'Science requires sacrifices.' },
    { id: 'pyramids', question: 'WHO BUILT THE PYRAMIDS?', answer: 'His opponents. Between respawns.\nThe shape was chosen for optimal matchmaking server cooling.' },
    { id: 'patch', question: 'CAN A PATCH NERF RADE?', answer: 'Patch notes are submitted to Rade for prior approval.\nNo objections have been recorded. No nerfs have survived.' },
    { id: 'queue', question: 'DOES SIGNING UP GUARANTEE A MATCH?', answer: 'It guarantees your name has reached the temple. The pharaoh chooses when to descend upon mid.' },
  ] },
  quote: { label: 'TEMPLE TRANSMISSION', warning: 'WARNING', transmission: 'RADE TRANSMISSION DETECTED', source: 'RADE KOMŠA / THE LIVING ARCHIVE', dismissal: 'ACKNOWLEDGED' },
  footer: { name: 'RADE KOMŠA', brand: 'MIDLANE SYSTEMS™', powered: 'Powered by completely unnecessary artificial intelligence.\nCooled by the Nile breeze.', status: 'ALL SYSTEMS OVERREACTING', terms: 'Terms of Midlane', protocol: 'Challenger Protocol', privacy: 'Neural Privacy', contact: 'Contact RADE AI', termsText: 'This is a free joke signup, not a tournament entry or a promise of a match. All performance claims and survival predictions are fictional. Submit only your own details. Repeated submissions do not improve your chances.', privacyText: 'While you complete the protocol, your answers, name, MMR, and description are stored only in your browser localStorage so progress is not lost. After final submission, the application is stored privately in Netlify Forms and the local draft is deleted. There is no public challenger list, analytics, or tracking cookies. Entries remain until the site operator deletes them. To request deletion, contact the person who shared this site and provide the name used in the application.', contactText: 'RADE AI cannot receive messages. Contact the person who shared this page for questions or removal requests.', verification: '*Not verified by Valve, God, science, or any recognized institution.', joke: 'This website is a joke. RADE AI does not exist. Probably.', valve: 'Dota 2 and Steam are trademarks of Valve Corporation. This project is not affiliated with or endorsed by Valve.', copyright: '© 2026 RADE MIDLANE SYSTEMS. ALL LANES RESERVED.' },
  errors: errors.en,
};
