export const errors = {
  sr: {
    invalidBody: 'Pošalji ispravne podatke za prijavu.',
    nick: 'Steam nick mora imati od 1 do 64 znaka, bez kontrolnih znakova.',
    link: 'Unesi HTTPS Steam Community link: /id/tvoj-nick ili /profiles/tvoj-17-cifreni-id, bez dodatnih parametara.',
    mmr: 'MMR mora biti ceo broj između 0 i 20.000.',
    method: 'Ovaj metod nije dozvoljen.',
    origin: 'Prijave sa drugih sajtova nisu dozvoljene.',
    contentType: 'Zahtev mora biti u application/json formatu.',
    large: 'Zahtev je prevelik. Ni faraonu ne treba toliko podataka.',
    rejected: 'Prijava je odbijena.',
    unavailable: 'Drevni server trenutno nije dostupan. Pokušaj ponovo kasnije.',
    rateLimit: 'Previše izazova. Sačekaj da se samopouzdanje ohladi pa pokušaj ponovo.',
    timeout: 'Potvrda kasni. Prijava je možda sačuvana; sačekaj pre novog pokušaja.',
    network: 'Veza je prekinuta. Prijava je možda sačuvana; sačekaj pre novog pokušaja.',
    required: 'Popuni sva tri polja. Proročanstvo nije zamena za podatke.',
    answers: 'Odgovori na sva pitanja pre završne presude.',
    challengerName: 'Ime mora imati od 1 do 80 znakova, bez kontrolnih znakova.',
    description: 'Napiši kratak razlog, do 500 znakova.',
    netlifyPreview: 'Čuvanje prijava radi na Netlify deployu. Lokalni pregled nije poslao podatke.',
  },
  en: {
    invalidBody: 'Send a valid signup object.',
    nick: 'Steam Nick must contain 1–64 characters without control characters.',
    link: 'Enter an HTTPS Steam Community link: /id/your-name or /profiles/your-17-digit-id, without extra parameters.',
    mmr: 'MMR must be a whole number between 0 and 20,000.',
    method: 'Method not allowed.',
    origin: 'Cross-origin submissions are not accepted.',
    contentType: 'Use application/json.',
    large: 'Request too large. Even a pharaoh needs less paperwork.',
    rejected: 'Submission rejected.',
    unavailable: 'The ancient server is unavailable. Please try again later.',
    rateLimit: 'Too many challenges. Let your confidence cool down and try again later.',
    timeout: 'Confirmation timed out. Your entry may have been saved; wait before trying again.',
    network: 'Connection interrupted. Your entry may have been saved; wait before trying again.',
    required: 'Complete all three fields. Prophecy is not a substitute for data.',
    answers: 'Answer every question before the final judgment.',
    challengerName: 'Name must contain 1–80 characters without control characters.',
    description: 'Write a short reason of up to 500 characters.',
    netlifyPreview: 'Submissions are saved on the Netlify deployment. This local preview did not send data.',
  },
};
