export const errors = {
  sr: {
    invalidBody: 'Pošalji ispravne podatke za prijavu.',
    steamId: 'Unesi SteamID64: 17 cifara Steam naloga, bez linka.',
    steamNotFound: 'Steam profil nije pronađen ili Steam nije vratio nick.',
    steamUnavailable: 'Steam trenutno nije dostupan. Pokušaj ponovo kasnije.',
    mmr: 'MMR mora biti ceo broj između 0 i 20.000.',
    method: 'Ovaj metod nije dozvoljen.',
    origin: 'Prijave sa drugih sajtova nisu dozvoljene.',
    contentType: 'Zahtev mora biti u application/json formatu.',
    large: 'Zahtev je prevelik. Ni faraonu ne treba toliko podataka.',
    rejected: 'Prijava je odbijena.',
    unavailable: 'Drevni server trenutno nije dostupan. Pokušaj ponovo kasnije.',
    rateLimit: 'Previše izazova. Sačekaj da se samopouzdanje ohladi pa pokušaj ponovo.',
    timeout: 'Potvrda kasni. Prijava je možda sačuvana; sačekaj pre novog pokušaja.',
    network: 'Veza je prekinuta. Prijava je možda sačuvana; sačekaj pre novog pokušaja.',
    required: 'Popuni sva tri polja. Proročanstvo nije zamena za podatke.',
    answers: 'Odgovori na sva pitanja pre završne presude.',
    description: 'Napiši kratak razlog, do 500 znakova.',
  },
  en: {
    invalidBody: 'Send a valid signup object.',
    steamId: 'Enter a SteamID64: the 17 digits of a Steam account, without a URL.',
    steamNotFound: 'Steam profile was not found or Steam did not return a nickname.',
    steamUnavailable: 'Steam is unavailable right now. Please try again later.',
    mmr: 'MMR must be a whole number between 0 and 20,000.',
    method: 'Method not allowed.',
    origin: 'Cross-origin submissions are not accepted.',
    contentType: 'Use application/json.',
    large: 'Request too large. Even a pharaoh needs less paperwork.',
    rejected: 'Submission rejected.',
    unavailable: 'The ancient server is unavailable. Please try again later.',
    rateLimit: 'Too many challenges. Let your confidence cool down and try again later.',
    timeout: 'Confirmation timed out. Your entry may have been saved; wait before trying again.',
    network: 'Connection interrupted. Your entry may have been saved; wait before trying again.',
    required: 'Complete all three fields. Prophecy is not a substitute for data.',
    answers: 'Answer every question before the final judgment.',
    description: 'Write a short reason of up to 500 characters.',
  },
};
