import { challengersContent } from './challengers.js';
import { errors } from './errors.js';

export default {
  challengers: challengersContent.sr,
  languages: { sr: 'SR', en: 'EN' },
  meta: { title: 'RADE KOMŠA — BOG MIDLEJNA | Hram večnog mida', description: '5.000 godina dominacije. Nijedan dostojan protivnik. Uđi u hram RADETA KOMŠE, faraona midlejna i životnog šahiste.' },
  a11y: { skip: 'Pređi na glavni sadržaj', nav: 'Glavna navigacija', language: 'Izaberi jezik', sr: 'Srpski', en: 'English', home: 'RADE KOMŠA — početak', quoteClose: 'Zatvori proročanstvo', pause: 'Zaustavi pokret', resume: 'Pokreni animacije', emblem: 'Zatraži proročanstvo faraona', stats: 'Statistika faraonske dominacije', chess: 'Zatraži potez životnog šahiste', judgment: 'Božanska presuda: dostojan pokušaja' },
  nav: { brand: 'RADE', sub: 'DINASTIJA MIDLEJNA', mythology: 'Sveti zapisi', chess: 'Životni šah', why: 'Zašto izazov', faq: 'Pitanja smrtnika', challenge: 'IZAZOVI' },
  hero: {
    era: 'OD 3000. P. N. E. / BEZ NERFOVA', status: 'BOŽANSKI SISTEM AKTIVAN', pretitle: 'FARAON MIDLEJNA', name: 'RADE KOMŠA', title: 'BOG MIDLEJNA',
    subtitle: '5.000 GODINA DOMINACIJE.\nNIJEDAN DOSTOJAN PROTIVNIK.', description: 'Zapisi o prvom meču izgubljeni su tokom pada Aleksandrijske biblioteke. Arheolozi još nisu pronašli dokaz da je Rade izgubio mid.', valve: 'Valve odbija da komentariše.', cta: 'IZAZOVI FARAONA I OSVOJI 50E', support: 'Jedno dugme. Jedna prijava. Jedan faraon koji čeka dokaz.', warning: 'RADE KOMŠA ne garantuje očuvanje MMR-a, samopouzdanja ili dostojanstva.',
    visualTop: 'BOŽANSTVO IDENTIFIKOVANO', visualId: 'DINASTIJA / 001', visualLabel: 'VEČNI MIDLEJNER', visualNote: 'ANUBIS REKE · ČUVAR ANCIENTA', coord: 'GIZA / MID KORIDOR', power: 'SNAGA: NEMERLJIVA', node: 'PIRAMIDALNI GPU KLASTER', uptime: 'RAD BEZ PREKIDA: 5.000 GODINA',
    rotations: ['ON NE IGRA MID. MID IGRA NJEGA.', 'ON NE ČITA MAPU. MAPA ČITA NJEGA.', 'ANCIENT JE PODIGNUT U NJEGOVU ČAST.', 'PRE DOTE BIO JE ŠAH. PRE ŠAHA BIO JE RADE.', 'BOGOVI EGIPTA SU IMALI MNOGO IMENA. MIDLEJN JE IMAO SAMO JEDNO.', 'RADE KOMŠA.'],
    badges: ['POKREĆE DREVNI AI', '14,7T BOŽANSKIH PARAMETARA', 'DOTA 2 VERIFIKOVANO*'],
  },
  ticker: 'RADE KOMŠA // BOG MIDLEJNA // ŽIVOTNI ŠAHISTA // FARAON MIDLEJNA // ANUBIS PROTOKOL AKTIVAN // BEŽITE NOBOVI // TEOLOŠKI MID DIFF // BOŽANSKI RED OTVOREN //',
  stats: [
    { label: 'POBEDE NA MIDU', note: 'Preostalih 0,03% je greška u prevodu papirusâ.' },
    { label: 'PORAŽENI IZAZIVAČI', note: 'Popis vodi Anubis. Rukom.' },
    { label: 'MORAL PROTIVNIKA U 10. MINUTU', note: 'Duša je već napustila lejning fazu.' },
    { label: 'KULE LIŠENE LJUDSKIH PRAVA', note: 'Ženevska konvencija nije učitana.' },
  ],
  oracle: {
    eyebrow: '01 / TEHNOLOGIJA PRE TEHNOLOGIJE', title: 'BOŽANSKI KOMPLEKS.\nSADA IMA API.', description: 'Piramide nisu grobnice. To su prvi matchmaking serveri. Mi smo im samo dodali RGB.', confidence: 'POUZDANOST PROROČANSTVA', review: 'RECENZIRAO RADE. ODOBRIO RADE.', name: 'RADE ORACLE™', subtitle: 'NEURALNI FARAONSKI POGON', status: 'POVEZAN SA VEČNOŠĆU', chart: 'SL. 01 — PROROČANSTVO OPTIMIZOVANO ZA GPU', gpu: 'GPU: 4.096 × SARKOFAG H100', action: 'KONSULTUJ PROROČIŠTE',
    telemetry: [
      { label: 'LAST HIT', value: 'PREDODREĐEN' }, { label: 'DENY', value: 'KANONSKI' }, { label: 'KONTROLA RUNA', value: 'BOŽANSKA' }, { label: 'DUBINA ŽIVOTNOG ŠAHA', value: '∞' }, { label: 'PREŽIVLJAVANJE GANKA', value: 'NEBITNO' }, { label: 'MORAL PROTIVNIKA', value: 'URUŠAVA SE' }, { label: 'VEZA SA ANUBISOM', value: 'AKTIVNA' }, { label: 'PIRAMIDALNI ČVOR', value: 'NA MREŽI' }, { label: 'STATUS ANCIENTA', value: 'ODBRANJEN' }, { label: 'MID RAZLIKA', value: 'TEOLOŠKA' },
    ],
  },
  mythology: {
    eyebrow: '02 / ARHIVA NEOSPORNIH ČINJENICA', title: 'ZAPISI IZ HRAMA MIDLEJNA', description: 'Istoriju pišu pobednici. Dakle, Rade.', tablet: 'PAPIRUS', action: 'PROČITAJ IZMEĐU HIJEROGLIFA',
    facts: [
      { id: 'first-creep', title: 'POSTANJE CREEPA', text: 'Prvi creep je spawnovan kako bi Rade imao šta da last hituje.' },
      { id: 'roshan', title: 'ZABRANJENA ETIMOLOGIJA', text: 'Roshan se prvobitno zvao Radešan. Skraćeno je zbog ograničenja interfejsa.' },
      { id: 'international', title: 'POREKLO INTERNATIONALA', text: 'The International je osnovan nakon neuspešnog pokušaja da se pronađe dostojan protivnik.' },
      { id: 'runes', title: 'KOSMIČKI RASPORED', text: 'Rune se pojavljuju na svaka dva minuta jer toliko dugo univerzum može da izdrži bez odavanja počasti Radetu.' },
      { id: 'fog', title: 'MILOST MAGLE', text: 'Fog of War postoji zato što običan čovek ne može bezbedno da posmatra sve što Rade vidi.' },
      { id: 'mmr', title: 'GRANICE MATEMATIKE', text: 'MMR meri udaljenost od Radetovog nivoa. Broj 10.000 predstavlja granicu sistema. Ne Radetovu granicu.' },
    ],
  },
  archaeology: { label: 'ARHEOLOŠKI IZVEŠTAJ #322', title: 'ZAPIS KOJI JE PROMENIO NAUKU.', text: 'Na zidu grobnice u Gizi pronađen je zapis koji približno glasi:', inscription: 'mid or feed', age: 'Starost zapisa procenjena je na 4.700 godina.', note: 'Stručna recenzija na čekanju.', coordinate: 'PLATO GIZE / SLOJ 7.39', seal: 'AUTENTIČNO\nJER RADE KAŽE' },
  chess: {
    eyebrow: '03 / STRATEGIJA IZNAD POSTOJANJA', title: 'ŽIVOTNI ŠAH™', subtitle: 'Dota je samo tabla.', text: 'Dok protivnik razmišlja o sledećem potezu, Rade razmišlja o sledećih sedam života.', detail: 'Za običnog čoveka postoje 64 polja. Za Radeta postoji beskonačna tabla.', doctrine: 'Svaki gank je gambit.\nSvaki creep je figura.\nSvaki poraz protivnika je teorijski očekivan.', name: 'POGON ŽIVOTNOG ŠAHA', depth: 'DUBINA', variations: 'IZRAČUNATE VARIJANTE', opponent: 'BUDUĆNOST PROTIVNIKA', known: 'POZNATA', rade: 'RADETOVA BUDUĆNOST', classified: 'POVERLJIVO', move: 'MAT ZA SEDAM ŽIVOTA', grandmaster: 'VELEMAJSTOR VEČNE TABLE', action: 'ZATRAŽI SLEDEĆI POTEZ',
  },
  why: { eyebrow: '02 / ZLATO, ČAST I LOŠE ODLUKE', title: 'ZAŠTO IZAZVATI RADETA?', note: 'TRI NAGRADE. JEDNA JE MOŽDA FINANSIJSKA.', cards: [
    { title: 'OSVOJI 50 EURA', text: 'Ako hram prihvati dokaz i Rade padne, faraonsko zlato prelazi u tvoje ruke. Porez Anubisu još nije definisan.', label: 'NAGRADNI FOND SARKOFAGA' },
    { title: 'ODNESI VEČNU ČAST', text: 'Pobeda nad Radetom vredi više od MMR-a: dobijaš pravo da kažeš da si nadigrao čoveka čiji ego ima sopstvenu piramidu.', label: 'TITULA ČUVARA MIDLEJNA' },
    { title: 'UĐI U PAPIRUSE', text: 'Čak i poraz ostavlja trag. Tvoje ime biće uklesano među smrtnike koji su prišli faraonu i ipak kliknuli final submit.', label: 'ARHIVA HRABRIH I NERAZUMNIH' },
  ] },
  science: { label: 'NAUKA JE REKLA SVOJE™', text: '„Nakon milijardi neuralnih simulacija, nije pronađen pouzdan dokaz o postojanju boljeg midlejnera.”', author: '— RADETOV INSTITUT ZA ISTRAŽIVANJE RADETA' },
  failures: {
    eyebrow: '03 / ARHIVA ODBIJENIH SMRTNIKA', title: 'NEUSPEŠNI\nCHALLENGI', description: 'Pre nego što zatražiš svojih 50 evra, pogledaj šta se desilo onima koji su verovali da mogu da ospore proročanstvo.', unsupported: 'Tvoj pregledač ne može da prikaže ovaj arhivski zapis.',
    entries: [
      { title: 'ARHIVSKI ZAPIS 0922', verdict: 'PRESUDA: HRAM NIJE IMPRESIONIRAN', aria: 'Pusti video neuspešnog challenga, arhivski zapis 0922' },
      { title: 'ARHIVSKI ZAPIS 0924', verdict: 'PRESUDA: FARAON OSTAJE NEOSPOREN', aria: 'Pusti video neuspešnog challenga, arhivski zapis 0924' },
    ],
  },
  bait: {
    challenge: 'IZAZOVI',
    immortal: 'DOKAŽI DA NIJE IMORTAL',
    better: 'DOKAŽI DA SI BOLJI',
    noob: 'DOKAŽI DA JE NOOB',
  },
  challenge: {
    back: 'Nazad u hram',
    eyebrow: 'SOCIJALNA TRKA / DOTA JE SAMO ALAT',
    title: 'KAKO OSVOJITI 50 EURA',
    lead: 'Ne osvajaš ovo klikom na MMR. Osvajaš dokazima, pritiskom, dogovorom i aurom koja može da preživi Radetov pogled.',
    reward: '50 EURA',
    rewardNote: 'Nagrada za dokaz koji hram prihvati kao dovoljno smeo.',
    howTitle: 'Dokaži jednu od tri stvari',
    rules: [
      'DOKAŽI DA SU BAJKE O TOME DA RADEKOMSA NIJE IMORTAL ISTINA',
      'DOKAŽI DA SI BOLJI OD RADEKOMSE FARAONA',
      'DOKAŽI DA IMAŠ AURICU',
    ],
    social: 'Svaka od ovih stvari je socijalna trka. Dota je samo alat. Prihvaćeno je sve: 1v1, 5v5, 3v3 ako se dogovorite.',
    modes: ['1v1', '3v3', '5v5', 'DOGOVOR HRAMA'],
    discord: 'Uđi na Discord, započni avanturu i ponesi dokaze.',
  },
  signup: {
    eyebrow: '01 / TVOJE IME. NJEGOVA STATISTIKA.', title: 'PROTOKOL\nIZAZIVAČA', subtitle: 'Hram će odabrati jednog izazivača za kog veruje da je dostojan. Mi ćemo mu se javiti i pozvati ga da se bori za 50 evra. Do tada, hram pamti svaki odgovor, čak i posle reload-a.', warning: 'SAMOPOUZDANJE NIJE KVALIFIKACIJA.', warningText: 'Hram prima sve MMR kategorije.\nRade ne priznaje nijednu.', facts: ['PET KORAKA', 'DRAFT SE ČUVA', 'JEDAN FARAON'], exit: 'Možeš da se vratiš na svaki odgovor pre konačnog slanja.', panel: 'UPIS U KNJIGU IZAZIVAČA / V.03', status: 'PRIMAMO SMRTNIKE', saved: 'DRAFT SAČUVAN', progressLabel: 'Napredak kroz protokol izazivača', stepCounter: 'KORAK', yes: 'DA', no: 'NE', unanswered: 'BEZ ODGOVORA', next: 'NASTAVI', back: 'NAZAD',
    step1: { kicker: 'I / STATUS SMRTNOSTI', question: 'DA LI STE I VI IMORTAL I DA LI MISLITE DA STE DOSTOJNI PROTIVNIK?', hint: 'Dve tvrdnje. Jedna odluka. Rade već zna istinu.' },
    step2: { kicker: 'II / TEST JERESI', question: 'DA LI VERUJETE U LAŽI DA RADE KOMŠA NIJE IMORTAL?', hint: 'Izaberite odgovor. Zatim overite svih pet pečata faraonske birokratije.' },
    step3: { kicker: 'III / MERENJE EGA', question: 'DA LI MISLITE DA STE BOLJI OD RADE KOMŠE?', hint: 'DA beži i ostaje zaključano 300 sekundi. Tek zatim Faraon dozvoljava da ga kliknete. NE je dostupno odmah.' },
    pursuit: { locked: 'FARAON JOŠ NE DOZVOLJAVA ODGOVOR DA', remaining: 'DO OTKLJUČAVANJA', unlocked: '300 SEKUNDI JE PROŠLO. DA JE SADA DOSTUPNO.', denied: 'Klik je odbijen. Anubis ne priznaje prečice.', note: 'Odbrojavanje počinje otvaranjem ovog pitanja. Hram pamti vreme i posle osvežavanja stranice.' },
    heresyWarnings: {
      label: 'UPOZORENJE / HRAM MIDLEJNA', counter: 'PEČAT', ok: 'OK', escape: 'Esc zatvara upozorenja i vraća na pitanje. Odgovor se potvrđuje tek posle svih pet pečata.',
      entries: [
        { title: 'ANUBIS VEĆ ZNA.', message: 'Upozorenje, Faraon Anubis će znati Vaš odgovor. Zapravo ga već zna. Ovaj prozor postoji radi papirologije.' },
        { title: 'TEOLOGIJA NE PRIMA ŽALBE.', message: 'Faraon Anubis je bog MIDLEJNA, ne možete kliknuti NE. Ako ste ipak kliknuli, Vaš miš će biti pozvan na informativni razgovor.' },
        { title: 'VAŠ EGO JE NA VAGI.', message: 'Na jedan tas stavljamo Vaše samopouzdanje. Na drugi Radetov poslednji last hit. Vaga je upravo podnela ostavku.' },
        { title: 'PAPIRUS PAMTI SVE.', message: 'Vaš odgovor biće uklesan u zid piramide. Brisanje istorije pregledača ne briše istoriju civilizacije.' },
        { title: 'POSLEDNJI PEČAT. ZA SADA.', message: 'Klikom na OK potvrđujete da ste upozoreni pet puta. Faraon zadržava pravo da Vaše mišljenje tretira kao dekoraciju.' },
      ],
    },
    step4: { kicker: 'IV / IDENTITET IZAZIVAČA', question: 'KO SE USUĐUJE DA PRIĐE MIDU?', hint: 'Ostavi podatke koji će biti upisani u Knjigu Izazivača.' },
    step5: { kicker: 'V / KONAČNA PRESUDA', question: 'DA LI STOJIŠ IZA OVOG IZAZOVA?', hint: 'Pregledaj odgovore. Ovo je jedini korak koji zaista šalje prijavu.' },
    steamIdentityHelp: 'Nalepi Steam profil, unesi kratko /id/ ime ili SteamID64. Nick preuzimamo sa Steama.', name: 'STEAM PROFIL ILI ID', mmr: 'DOTA 2 MMR', description: 'ZAŠTO SI DOSTOJAN?', required: 'OBAVEZNO', honest: 'BUDI ISKREN. ON ZNA.', descriptionLimit: 'DO 500 ZNAKOVA', namePlaceholder: 'https://steamcommunity.com/id/sn0w98/', mmrPlaceholder: '5000', descriptionPlaceholder: 'Ukratko objasni zašto baš ti zaslužuješ mid protiv Radeta...', honeypot: 'Ostavi prazno', analysis: 'RADE AI je spreman da zabeleži tvoju odluku.', submit: 'POŠALJI KONAČAN IZAZOV', private: 'Prijava se čuva u Cloudflare D1 i prikazuje u javnoj arhivi izazivača. Dostojanstvo nije obuhvaćeno garancijom.', privacy: 'Kako čuvamo podatke',
    reviewImmortal: 'IMORTAL I DOSTOJAN', reviewLies: 'VERUJE U LAŽI', reviewBetter: 'BOLJI OD RADETA', reviewName: 'STEAM PROFIL', reviewMmr: 'MMR', reviewDescription: 'RAZLOG',
    processingLabel: 'DREVNA PROCENA U TOKU', processingNote: 'Ne prekidaj vezu sa svojom zabludom.', awaiting: 'ČEKANJE POTVRDE IZ KNJIGE IZAZIVAČA...',
    stages: ['POVEZIVANJE SA DREVNIM SERVEROM...', 'SKENIRANJE STEAM PROFILA...', 'PROVERA MMR-a...', 'ANALIZA SAMOPOUZDANJA...', 'KONSULTOVANJE ANUBISA...', 'SIMULACIJA 14.882.943 MEČA...', 'RADE NEURAL CORE DONOSI PRESUDU...'],
    acceptedLabel: 'PRESUDA JE ZABELEŽENA', accepted: 'IZAZOV JE PRIHVAĆEN.', acceptedText: 'Tvoje ime je upisano u Knjigu Izazivača.', survival: 'Predviđena verovatnoća preživljavanja:', survivalNote: 'Proračun proročanstva. Bez naučne vrednosti.', luck: 'Srećno.\nTrebaće ti.', return: 'POVRATAK U SVET SMRTNIKA', stamp: 'DOSTOJAN POKUŠAJA', stampNote: 'Dostojnost pokušaja ne podrazumeva dostojnost Radeta.', judgmentLabel: 'ANUBIS JE IZMERIO TVOJ MMR',
  },
  faq: { eyebrow: '04 / ODGOVORI UKLESANI U KAMEN', title: 'PITANJA KOJA SMRTNICI\nČESTO POSTAVLJAJU', description: 'Sumnja je ljudska. Odgovori su konačni.', entries: [
    { id: 'doctor', question: 'DA LI JE RADE KOMŠA DOKTOR?', answer: 'DA.\nRADE KOMŠA JE DOKTOR SVAKOG HEROJA.\nDiploma nije pronađena jer je papir izmišljen nakon njegove specijalizacije.' },
    { id: 'heroes', question: 'DA LI RADE KOMŠA IGRA SVAKOG HEROJA?', answer: 'Pogrešno pitanje.\nHeroji igraju za RADETA.' },
    { id: 'main', question: 'KOJI JE RADETOV MAIN HERO?', answer: 'DOTA 2.' },
    { id: 'rating', question: 'KOLIKI MMR IMA RADE?', answer: 'MMR sistem trenutno ne podržava potrebnu širinu broja.' },
    { id: 'lost', question: 'DA LI JE RADE IKADA IZGUBIO MID?', answer: 'Ne postoje pouzdani istorijski izvori koji potvrđuju takav događaj.\n\nNeki protivnici tvrde suprotno.\nNjihovi Steam profili više nisu relevantni za istraživanje.' },
    { id: 'pharaoh', question: 'DA LI JE RADE FARAON?', answer: 'Istoričari koriste termin „faraon” jer savremena nauka još nema precizniji izraz.' },
    { id: 'god', question: 'DA LI JE RADE BOG MIDLEJNA?', answer: 'Ovo je FAQ, ne mesto za raspravu o opštepoznatim činjenicama.' },
    { id: 'anubis', question: 'ZAŠTO JE ANUBIS NA SAJTU?', answer: 'Anubis je zadužen za protivnike nakon lane faze.' },
    { id: 'chess', question: 'DA LI RADE IGRA ŠAH?', answer: 'Rade ne igra šah.\nRade igra životni šah.\nŠah je samo pojednostavljena verzija.' },
    { id: 'gank', question: 'MOŽE LI SE RADE GANKOVATI?', answer: 'Teoretski da.\nEksperimentalna potvrda još nije uspešno ponovljena.' },
    { id: 'challengers', question: 'ZAŠTO SE PRIJAVLJUJU IZAZIVAČI?', answer: 'Nauka zahteva žrtve.' },
    { id: 'pyramids', question: 'KO JE IZGRADIO PIRAMIDE?', answer: 'Protivnici. Između dva respawna.\nOblik je izabran radi optimalnog hlađenja matchmaking servera.' },
    { id: 'patch', question: 'MOŽE LI PATCH DA NERFUJE RADETA?', answer: 'Patch notes se prvo šalju Radetu na odobrenje.\nDo sada nije bilo primedbi. Ni preživelih nerfova.' },
    { id: 'queue', question: 'DA LI PRIJAVA GARANTUJE MEČ?', answer: 'Prijava garantuje da je tvoje ime stiglo do hrama. Faraon sam bira trenutak silaska na mid.' },
  ] },
  quote: { label: 'PRENOS IZ HRAMA', warning: 'UPOZORENJE', transmission: 'DETEKTOVAN RADETOV PRENOS', source: 'RADE KOMŠA / ŽIVA ARHIVA', dismissal: 'PRIMLJENO' },
  footer: { name: 'RADE KOMŠA', brand: 'SISTEMI MIDLEJNA™', powered: 'Pokreće potpuno nepotrebna veštačka inteligencija.\nHladi ga povetarac sa Nila.', status: 'SVI SISTEMI PRETERUJU', terms: 'Zakoni midlejna', protocol: 'Protokol izazivača', privacy: 'Neuralna privatnost', contact: 'Kontaktiraj RADE AI', termsText: 'Ovo je besplatna šaljiva prijava, a ne ulaznica za turnir niti obećanje meča. Tvrdnje o učinku i prognoze preživljavanja su izmišljene. Pošalji samo svoje podatke. Nova prijava ne povećava šanse.', privacyText: 'Dok popunjavaš protokol, odgovori, Steam profil ili ID, MMR i opis čuvaju se samo u localStorage-u tvog pregledača kako se napredak ne bi izgubio. Nakon konačnog slanja, SteamID64, Steam nick sa Steam profila, MMR, razlog i tri DA/NE odgovora čuvaju se u Cloudflare D1 i prikazuju u javnoj arhivi izazivača i lokalni draft se briše. Presuda je takođe javna. Nema analitike ni kolačića za praćenje. Prijave ostaju dok ih administrator ne obriše. Za brisanje se obrati osobi koja ti je poslala ovaj sajt i navedi ime iz prijave.', contactText: 'RADE AI ne prima poruke. Za pitanja i brisanje podataka obrati se osobi koja ti je poslala ovaj sajt.', verification: '*Nisu verifikovali Valve, Bog, nauka niti bilo koja priznata ustanova.', joke: 'Ovaj sajt je šala. RADE AI ne postoji. Verovatno.', valve: 'Dota 2 i Steam su robne marke kompanije Valve Corporation. Projekat nije povezan sa kompanijom Valve niti ima njenu podršku.', copyright: '© 2026 RADE MIDLANE SYSTEMS. SVI LEJNOVI ZADRŽANI.' },
  errors: errors.sr,
};
