// One page of semantic markup; every text node is populated from the dictionaries.
export function createLayout(i18n) {
  const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const text = key => `<span data-i18n="${key}">${escape(i18n.t(key))}</span>`;
  const aria = key => `data-i18n-aria-label="${key}" aria-label="${escape(i18n.t(key))}"`;
  const placeholder = key => `data-i18n-placeholder="${key}" placeholder="${escape(i18n.t(key))}"`;
  const eye = '<span class="eye-symbol" aria-hidden="true"><i></i></span>';
  const heading = section => `<span class="eyebrow">${text(`${section}.eyebrow`)}</span><h2>${text(`${section}.title`)}</h2>`;
  const counter = (value, decimals = 0) => `<span data-count="${value}" data-decimals="${decimals}">${i18n.format(0, decimals)}</span>`;
  const brand = `<span class="brand-mark" aria-hidden="true">𓂀</span><span>${text('nav.brand')}<small>${text('nav.sub')}</small></span>`;
  const challengerForm = `<div class="form-panel protocol-panel panel"><div class="panel-heading"><span>${text('signup.panel')}</span><span class="online"><i class="live-dot"></i>${text('signup.status')}</span></div>
    <form id="signup-form" name="radekomsa-challenger" method="POST" novalidate><input id="immortalWorthy" type="hidden" name="immortalWorthy"><input id="believesRadeMortal" type="hidden" name="believesRadeMortal"><input id="betterThanRade" type="hidden" name="betterThanRade"><input id="lieYesAttempts" type="hidden" name="lieYesAttempts" value="0"><input id="superiorityEvades" type="hidden" name="superiorityEvades" value="0"><input id="submissionLanguage" type="hidden" name="submissionLanguage" value="sr"><input id="submittedAt" type="hidden" name="submittedAt"><div class="honeypot" aria-hidden="true"><label for="website">${text('signup.honeypot')}</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div>
    <div class="protocol-progress"><span id="step-counter" class="micro" aria-live="polite"></span><span class="draft-state"><i class="status-dot"></i>${text('signup.saved')}</span></div><ol class="step-track" ${aria('signup.progressLabel')}>${[1, 2, 3, 4, 5].map(step => `<li data-progress-step="${step}"><span>${step}</span></li>`).join('')}</ol>
    <section class="form-step" data-step="1" aria-labelledby="step-1-title"><span class="step-kicker">${text('signup.step1.kicker')}</span><h3 id="step-1-title" tabindex="-1">${text('signup.step1.question')}</h3><p>${text('signup.step1.hint')}</p><div class="choice-grid"><button class="choice-button" type="button" data-answer="immortalWorthy" data-value="yes" aria-pressed="false">${text('signup.yes')}</button><button class="choice-button" type="button" data-answer="immortalWorthy" data-value="no" aria-pressed="false">${text('signup.no')}</button></div></section>
    <section class="form-step" data-step="2" aria-labelledby="step-2-title" hidden><span class="step-kicker">${text('signup.step2.kicker')}</span><h3 id="step-2-title" tabindex="-1">${text('signup.step2.question')}</h3><p>${text('signup.step2.hint')}</p><div class="choice-grid truth-choices"><button id="lie-yes" class="choice-button" type="button" data-answer="believesRadeMortal" data-value="yes" aria-pressed="false">${text('signup.yes')}</button><button id="lie-no" class="choice-button" type="button" data-answer="believesRadeMortal" data-value="no" aria-pressed="false">${text('signup.no')}</button></div></section>
    <section class="form-step" data-step="3" aria-labelledby="step-3-title" hidden><span class="step-kicker">${text('signup.step3.kicker')}</span><h3 id="step-3-title" tabindex="-1">${text('signup.step3.question')}</h3><p>${text('signup.step3.hint')}</p><div id="evasive-arena" class="evasive-arena"><button id="better-yes" class="choice-button evasive-yes" type="button" aria-disabled="true" aria-describedby="pursuit-status pursuit-note" data-answer="betterThanRade" data-value="yes" aria-pressed="false">${text('signup.yes')}</button><button id="better-no" class="choice-button evasive-no" type="button" data-answer="betterThanRade" data-value="no" aria-pressed="false">${text('signup.no')}</button><span class="arena-glyph" aria-hidden="true">𓂀</span></div><div class="pursuit-info"><p id="pursuit-status" role="status">${text('signup.pursuit.locked')}</p><div class="pursuit-countdown" id="pursuit-countdown"><span>${text('signup.pursuit.remaining')}</span><strong id="pursuit-clock" role="timer" aria-live="off">05:00</strong></div><p id="pursuit-feedback" class="pursuit-feedback" role="status"></p><small id="pursuit-note">${text('signup.pursuit.note')}</small></div></section>
    <section class="form-step" data-step="4" aria-labelledby="step-4-title" hidden><span class="step-kicker">${text('signup.step4.kicker')}</span><h3 id="step-4-title" tabindex="-1">${text('signup.step4.question')}</h3><p>${text('signup.step4.hint')}</p><div class="field"><label for="challengerName">${text('signup.name')}<small>${text('signup.required')}</small></label><input id="challengerName" name="challengerName" ${placeholder('signup.namePlaceholder')} maxlength="80" required autocomplete="name" aria-describedby="form-error"></div><div class="field"><label for="mmr">${text('signup.mmr')}<small>${text('signup.honest')}</small></label><input id="mmr" name="mmr" type="number" min="0" max="20000" step="1" ${placeholder('signup.mmrPlaceholder')} required inputmode="numeric" aria-describedby="form-error"></div><div class="field"><label for="description">${text('signup.description')}<small>${text('signup.descriptionLimit')}</small></label><textarea id="description" name="description" ${placeholder('signup.descriptionPlaceholder')} maxlength="500" required aria-describedby="description-count form-error"></textarea><small id="description-count" class="character-count"></small></div></section>
    <section class="form-step review-step" data-step="5" aria-labelledby="step-5-title" hidden><span class="step-kicker">${text('signup.step5.kicker')}</span><h3 id="step-5-title" tabindex="-1">${text('signup.step5.question')}</h3><p>${text('signup.step5.hint')}</p><dl class="review-list"><div><dt>${text('signup.reviewImmortal')}</dt><dd id="review-immortal"></dd></div><div><dt>${text('signup.reviewLies')}</dt><dd id="review-lies"></dd></div><div><dt>${text('signup.reviewBetter')}</dt><dd id="review-better"></dd></div><div><dt>${text('signup.reviewName')}</dt><dd id="review-name"></dd></div><div><dt>${text('signup.reviewMmr')}</dt><dd id="review-mmr"></dd></div><div class="review-description"><dt>${text('signup.reviewDescription')}</dt><dd id="review-description"></dd></div></dl><p class="analysis-line"><i class="live-dot"></i>${text('signup.analysis')}</p></section>
    <p id="form-error" class="error" role="alert" hidden></p><div class="step-actions"><button id="back-button" class="back-button" type="button"><span aria-hidden="true">←</span>${text('signup.back')}</button><button id="next-button" class="button secondary" type="button">${text('signup.next')}<span aria-hidden="true">→</span></button><button id="submit-button" class="button primary submit" type="submit" hidden>${text('signup.submit')}<span aria-hidden="true">↗</span></button></div><p class="form-note">${text('signup.private')}<br><a href="#privacy">${text('signup.privacy')}</a></p></form>
    <div id="processing" class="result" hidden tabindex="-1"><div class="processing-orb" aria-hidden="true">𓆣</div><span class="micro gold">${text('signup.processingLabel')}</span><h3 id="processing-text" role="status"></h3><div class="processing-track" aria-hidden="true"><i></i></div><p>${text('signup.processingNote')}</p></div><div id="success" class="result" hidden tabindex="-1">${eye}<span class="micro online">${text('signup.acceptedLabel')}</span><h3>${text('signup.accepted')}</h3><p>${text('signup.acceptedText')}</p><div class="verdict-stamp">${text('signup.stamp')}</div><small class="muted stamp-note">${text('signup.stampNote')}</small><div class="survival"><span>${text('signup.survival')}</span><strong id="survival"></strong><small>${text('signup.survivalNote')}</small></div><p class="luck">${text('signup.luck')}</p><button id="return-button" class="button secondary" type="button">${text('signup.return')}<span aria-hidden="true">↗</span></button></div></div>`;

  const heresyDialog = `<dialog id="heresy-dialog" class="heresy-dialog" aria-labelledby="heresy-title" aria-describedby="heresy-message">
    <div class="heresy-heading"><span aria-hidden="true">𓂀</span><span>${text('signup.heresyWarnings.label')}</span><span class="micro" data-warning-count></span></div>
    <div class="heresy-body"><div class="heresy-seal" aria-hidden="true">𓋹</div><div aria-live="polite" aria-atomic="true"><h3 id="heresy-title" data-warning-title></h3><p id="heresy-message" data-warning-message></p></div><button type="button" class="button primary heresy-ok" data-warning-ok>${text('signup.heresyWarnings.ok')}</button><small>${text('signup.heresyWarnings.escape')}</small></div>
    <div class="heresy-progress" aria-hidden="true"><i data-warning-progress></i></div>
  </dialog>`;

  return `
  ${heresyDialog}
  <a class="skip-link" href="#main">${text('a11y.skip')}</a>
  <div class="ambient" aria-hidden="true"><div class="orb orb-one"></div><div class="orb orb-two"></div><div id="particles"></div></div>
  <div class="topbar"><div class="wrap"><span>${text('hero.era')}</span><span><i class="live-dot"></i>${text('hero.status')}</span></div></div>
  <header class="header wrap"><a class="brand" href="#home" data-quote-trigger="logo" ${aria('a11y.home')}>${brand}</a><nav ${aria('a11y.nav')}><a class="nav-challenge challenge-cta" href="#challenge">${text('nav.challenge')}</a><a href="#why">${text('nav.why')}</a><a href="#faq">${text('nav.faq')}</a></nav><div class="header-controls"><div class="language-switch" role="group" ${aria('a11y.language')}><button type="button" data-language="sr" ${aria('a11y.sr')} aria-pressed="true">${text('languages.sr')}</button><span aria-hidden="true">|</span><button type="button" data-language="en" ${aria('a11y.en')} aria-pressed="false">${text('languages.en')}</button></div><button class="motion-toggle" type="button" id="motion-toggle" ${aria('a11y.pause')}><span aria-hidden="true">Ⅱ</span></button></div></header>
  <main id="main">
    <div id="home" class="home-view">
    <section class="hero wrap" aria-labelledby="hero-title"><div class="hero-copy"><span class="eyebrow hero-eyebrow"><span aria-hidden="true">𓆣</span>${text('hero.pretitle')}<span class="eyebrow-rule"></span></span><h1 id="hero-title">${text('hero.name')}<strong>${text('hero.title')}</strong></h1><p class="hero-subtitle">${text('hero.subtitle')}</p><p class="hero-description">${text('hero.description')} <em>${text('hero.valve')}</em></p><a href="#challenge" class="button primary challenge-cta hero-prize-cta">${text('hero.cta')}<span aria-hidden="true">↗</span></a><p class="cta-support">${text('hero.support')}</p><div class="hero-clickbait-row"><a class="bait-cta challenge-cta hero-bait" href="#challenge"><span aria-hidden="true">𓆣</span>${text('bait.challenge')}</a></div><div class="hero-badges">${i18n.t('hero.badges').map((_, i) => i === 2 ? `<a class="badge" href="#disclaimer" data-quote-trigger="badge"><span aria-hidden="true">◈</span>${text(`hero.badges.${i}`)}</a>` : `<button class="badge" type="button" data-quote-trigger="badge"><span aria-hidden="true">✧</span>${text(`hero.badges.${i}`)}</button>`).join('')}</div><p class="hero-warning">${text('hero.warning')}</p></div>
    <div class="pharaoh-panel"><div class="visual-top"><span><i class="live-dot"></i>${text('hero.visualTop')}</span><span>${text('hero.visualId')}</span></div><div class="pharaoh-scene"><div class="sun-disc" aria-hidden="true"></div><div class="orbit orbit-a" aria-hidden="true"></div><div class="orbit orbit-b" aria-hidden="true"></div><div class="hieroglyph-ring" aria-hidden="true">𓂀　𓆣　𓋹　𓊹　𓅃　𓂀　𓆣</div><div class="pyramid pyramid-left" aria-hidden="true"></div><div class="pyramid pyramid-right" aria-hidden="true"></div><div class="obelisk obelisk-left" aria-hidden="true"></div><div class="obelisk obelisk-right" aria-hidden="true"></div><button class="pharaoh-emblem" type="button" data-quote-trigger="decoration" ${aria('a11y.emblem')}><span class="pharaoh-collar" aria-hidden="true"></span><span class="nemes" aria-hidden="true"></span><span class="pharaoh-face" aria-hidden="true"><span class="pharaoh-brow"></span><span class="pharaoh-eyes"></span><span class="pharaoh-nose"></span><span class="pharaoh-beard"></span></span><span class="uraeus" aria-hidden="true">𓋹</span></button><div class="coordinates"><span>${text('hero.coord')}</span><span>${text('hero.power')}</span></div><div class="scan-line" aria-hidden="true"></div></div><div class="entity-label"><span class="micro">${text('hero.visualNote')}</span><strong>${text('hero.visualLabel')}</strong><span class="micro entity-glyphs" aria-hidden="true">𓂀 ─── 𓆣 ─── 𓂀</span></div><div class="visual-bottom"><span>${text('hero.node')}</span><span class="signal" aria-hidden="true">▂▄▆█</span></div></div></section>
    <div class="rotating-prophecy wrap"><span class="prophecy-mark" aria-hidden="true">𓋹</span><p id="rotating-subtitle"></p><span class="micro">${text('hero.uptime')}</span></div>
    <div class="ticker"><div class="ticker-track"><span data-i18n="ticker">${escape(i18n.t('ticker'))}</span><span data-i18n="ticker" aria-hidden="true">${escape(i18n.t('ticker'))}</span></div></div>
    <section class="stats wrap" ${aria('a11y.stats')}>${[99.97, 8492, 3, 14208].map((value, i) => `<div><span class="micro">${text(`stats.${i}.label`)}</span><strong class="${i === 2 ? 'danger' : ''}">${counter(value, i === 0 ? 2 : 0)}${i === 0 || i === 2 ? '<em>%</em>' : ''}</strong><small>${text(`stats.${i}.note`)}</small></div>`).join('')}</section>
    <div class="bait-ribbon wrap"><a class="bait-cta challenge-cta" href="#challenge"><span aria-hidden="true">𓋹</span>${text('bait.immortal')}</a></div>
    <section class="challenge-page section" id="challenge" aria-labelledby="challenge-title"><div class="challenge-shell wrap" id="signup"><div class="challenge-brief"><span class="eyebrow">${text('signup.eyebrow')}</span><h2 id="challenge-title">${text('signup.title')}</h2><p class="challenge-lead">${text('signup.subtitle')}</p><div class="reward-slab"><span>${text('challenge.reward')}</span><small>${text('challenge.rewardNote')}</small></div><div class="warning"><span aria-hidden="true">𓂀</span><div><strong>${text('signup.warning')}</strong><p>${text('signup.warningText')}</p></div></div><div class="signup-facts">${i18n.t('signup.facts').map((_, i) => `<span><span aria-hidden="true">✓ </span>${text(`signup.facts.${i}`)}</span>`).join('')}</div><small class="muted">${text('signup.exit')}</small><div class="signup-ornament" aria-hidden="true">𓅃 ─── 𓂀 ─── 𓅃</div></div>${challengerForm}</div></section>
    <section class="why section wrap" id="why"><div class="section-heading"><div>${heading('why')}</div><span class="micro muted">${text('why.note')}</span><a class="bait-cta challenge-cta" href="#challenge"><span aria-hidden="true">♜</span>${text('bait.better')}</a></div><div class="why-grid">${i18n.t('why.cards').map((_, i) => `<article class="why-card"><div class="card-top"><span aria-hidden="true">${['⌖', '𓂀', '♜'][i]}</span><span class="micro">0${i + 1}</span></div><h3>${text(`why.cards.${i}.title`)}</h3><p>${text(`why.cards.${i}.text`)}</p><span class="micro gold">${text(`why.cards.${i}.label`)}</span></article>`).join('')}</div></section>
    <section class="science wrap"><span class="micro">${text('science.label')}</span><blockquote>${text('science.text')}</blockquote><span class="micro muted">${text('science.author')}</span></section>
    <section class="failures section wrap" id="failures"><div class="section-heading"><div>${heading('failures')}</div><p>${text('failures.description')}</p></div><div class="failure-grid">${i18n.t('failures.entries').map((_, i) => `<article class="failure-record"><div class="failure-media"><video controls playsinline preload="metadata" poster="/videos/failed-challenge-0${i + 1}.jpg" ${aria(`failures.entries.${i}.aria`)}><source src="/videos/failed-challenge-0${i + 1}.m4v" type="video/mp4">${text('failures.unsupported')}</video><span class="failure-index" aria-hidden="true">0${i + 1} / 𓂀</span></div><div class="failure-caption"><h3>${text(`failures.entries.${i}.title`)}</h3><span>${text(`failures.entries.${i}.verdict`)}</span></div></article>`).join('')}</div></section>
    <section class="faq section wrap" id="faq"><div class="section-heading"><div>${heading('faq')}</div><p>${text('faq.description')}</p><a class="bait-cta challenge-cta" href="#challenge"><span aria-hidden="true">◈</span>${text('bait.noob')}</a></div><div class="faq-list">${i18n.t('faq.entries').map((entry, i) => `<details data-faq-id="${entry.id}"><summary><span class="faq-number" aria-hidden="true">${String(i + 1).padStart(2, '0')}</span><span>${text(`faq.entries.${i}.question`)}</span><span class="faq-plus" aria-hidden="true">+</span></summary><div class="faq-answer"><span class="faq-glyph" aria-hidden="true">𓂀</span><p>${text(`faq.entries.${i}.answer`)}</p></div></details>`).join('')}</div></section>
    </div>
  </main>
  <footer class="wrap"><div class="footer-top"><a class="brand" href="#home" data-quote-trigger="logo"><span class="brand-mark" aria-hidden="true">𓂀</span><span>${text('footer.name')}<small>${text('footer.brand')}</small></span></a><p>${text('footer.powered')}</p><span class="footer-status"><i class="live-dot"></i>${text('footer.status')}</span></div><div class="footer-links"><a href="#terms">${text('footer.terms')}</a><a href="#challenge" class="challenge-cta">${text('footer.protocol')}</a><a href="#privacy">${text('footer.privacy')}</a><a href="#contact">${text('footer.contact')}</a></div><div class="legal-details">${['terms', 'privacy', 'contact'].map(key => `<details id="${key}"><summary>${text(`footer.${key}`)}</summary><p>${text(`footer.${key}Text`)}</p></details>`).join('')}</div><div class="disclaimers" id="disclaimer"><p>${text('footer.verification')}</p><p>${text('footer.joke')}</p><p>${text('footer.valve')}</p><span>${text('footer.copyright')}</span></div></footer>
  <aside id="quote-toast" class="quote-toast" hidden><button id="quote-close" type="button" ${aria('a11y.quoteClose')}><span aria-hidden="true">×</span></button><div class="quote-heading"><span aria-hidden="true">𓂀</span><span id="quote-label"></span></div><div id="quote-announcement" role="status" aria-live="polite" aria-atomic="true"><p id="quote-text"></p></div><span class="micro muted">${text('quote.source')}</span><div class="quote-timer" aria-hidden="true"></div></aside>
  <div id="judgment" class="judgment" hidden aria-hidden="true"><div class="judgment-halo">${eye}<div class="judgment-glyphs">𓂀　𓆣　𓋹　𓅃　𓂀</div><span class="micro">${text('signup.judgmentLabel')}</span><strong>${text('signup.stamp')}</strong></div></div>`;
}
